[platformio]
include_dir  = include
src_dir      = src
default_envs = native

[env:native]
platform=native
build_flags =
    -g
    -D DESKTOP_SIM
    -D PIO_VERBOSE=1
    -lSDL
build_src_filter =
    +<*.cpp>
    -<stm32main.cpp>

[env:stm32h7]
platform=ststm32
framework=arduino
board=weact_mini_h743vitx
lib_ldf_mode = chain+
build_flags =
    -g
    -D PIO_VERBOSE=1
    -DHSE_VALUE=25000000

build_src_filter =
    +<*.cpp>
    -<pcmain.cpp>
